### ISSUE TITLE
(Enhancement) Hoopster's enhanced speed option when the player overlaps its X-position

### ISSUE THREAD

**Issue by P-Star7** [TheXTech/TheXTech#250]
An NPC option for Hoopsters to increase their speed by double if the player is currently at its X-position, as in SMB2. This means that if any pixel of the player's hitbox is at the same X position as any pixel of the Hoopster's hitbox, it goes into fast mode. This is to allow for NPC-code modified Hoopsters to work correctly. I'm sure the algorithm could be optimized for 3DS and Vita by only checking the leftmost and rightmost pixels of the hitboxes, and toggling the Hoopster's fast mode on and off only once that change is detected instead of checking for an x-position overlap every frame, but even the unoptimized one will work on computer/Android.

**Comment by Wohlstand** [comment]
I still kept this thing in my mind to make that. Since I met SMBX, I found hoopsters work wrongly: they must increase their movement speed in only condition the player stands under them, but moves normally always when the player stands away. Could add a special value with two behavior modes: SMBX mode, and SMB2 mode (close to original behaviour)
