### ISSUE TITLE
[Vanilla BUG] Piranha Plant bug with "no turn back" enabled

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#470]
It plays "Shell Hit" sound when piranha plant vanishes with "no turn back" (screenlock). This is annoying.

**Comment by ds-sloth** [comment]
If it's only modifying a PlaySound call, I think it's reasonable to not make any compat flag for this, or possibly just guard it behind the new Modern SFX config flag in 1.3.7.

**Comment by Wohlstand** [comment]
Better to improve the death logic of these piranhas in the condition they died because they were "squashed" by a moved screen's border, so, they became out of the section's area. PlaySound is just a dumb method to play a sound by request. But it can be used in a debugger to catch the source of the command in a debugger, and then modify the logic at that side.

**Comment by ds-sloth** [comment]
If we're modifying the death logic then it will require a compat flag, and I'm not sure if this is an important enough change to add one.

**Comment by Wohlstand** [comment]
When this logic doesn't affect the workflow (just playing or NOT playing a sound), then it isn't a valuable change to require a compat flag. However, I added some for the swooper.

**Comment by ds-sloth** [comment]
Then, I think we agree with each other on this point. As long as the only death logic we are improving is sound-related, it's fine.

**Comment by ds-sloth** [comment]
This should be fixed now -- I'm sorry for the very long wait. Can you please confirm?

**Comment by LoveBodhi** [comment]
https://github.com/TheXTech/TheXTech/assets/37089530/c58f220c-7487-4e0a-8062-dc7d18a809bc

Fixed: OBS 25 doesn't support OpenGL Renderer, sorry... I have to use SDL2 instead...
