### ISSUE TITLE
UI doesn't do well with very long controller names

### ISSUE THREAD

**Issue by 0lhi** [TheXTech/TheXTech#559]
![Scr_2023-07-16_22-04-38](https://github.com/Wohlstand/TheXTech/assets/74732674/ab497baa-cf37-459a-b90b-98b62b682bd9)
![Scr_2023-07-16_22-06-36](https://github.com/Wohlstand/TheXTech/assets/74732674/f4910be0-cadf-4b90-9d7a-a4eaa547c8ab)

**Comment by ds-sloth** [comment]
I've tried my best to address this. The current strategy is to split the SDL-produced string into words, and then make the following abbreviations:

"generic" -> "gen"
"Nintendo" -> "N"
"Microsoft" -> "M"
"Sony" -> "S"
"PlayStation" -> "PS"
"controller" -> "c"
"joystick" -> "joy"
"standard" -> "std"

And connection words are ignored:

"usb" -> ""
"bluetooth" -> ""

Finally, if the string is already 10 characters long or longer, no additional words will be added to the string.

Please let me know how this looks to you. We can change it further if needed; I've refactored the code so that this logic is in its own function: `joystick.cpp:s_GetJoystickName`.

**Comment by Wohlstand** [comment]
Good idea

**Comment by 0lhi** [comment]
For reasons I don't know my Computer doesn't work with Xinput Controllers currently. Other programs are also affected. I can only test with my DirectInput Controllers:

![Scr_2023-08-19_18-29-59_(1)](https://github.com/Wohlstand/TheXTech/assets/74732674/0c591e05-d28e-4999-b628-7a5d9f3db801)
![Scr_2023-08-19_18-33-17](https://github.com/Wohlstand/TheXTech/assets/74732674/6a4dc115-f749-4489-ba3a-169370bd66b4)
![Scr_2023-08-19_18-37-10](https://github.com/Wohlstand/TheXTech/assets/74732674/fc226e59-c180-4275-9e68-afadbd943a86)

**Comment by ds-sloth** [comment]
Very strange that the last one was called "Logitech Logitech". Maybe I should try to de-duplicate them?

**Comment by 0lhi** [comment]
Yeah. Also, it doesn't seem to stop after 10 chars like you said? Imo that should be a hard limit for every usecase.

**Comment by ds-sloth** [comment]
So, it doesn't start a new word if there are more than 10 chars already. "Logitech " has 9 characters so it's willing to add the next "Logitech".

I can set it up to cutoff at 10 chars, or to not start a new word if it would result in there being more than 10 chars. ("Logitech Logitech" has 17 chars, more than 10, so the second "Logitech" would be rejected.)

**Comment by 0lhi** [comment]
Not starting sounds good. What do you think would be better for second pic, ignore "HID" or treat `:` as equivalent to a space?

**Comment by ds-sloth** [comment]
Please test this again now, I think I've figured both issues out.

**Comment by 0lhi** [comment]
DragonRise, Logitech, and:

![Scr_2023-08-19_22-33-43](https://github.com/Wohlstand/TheXTech/assets/74732674/9ff78381-a195-4708-bd57-738a82fe05ad)

I think this can be removed from 1.3.6.1 Milestones, though I'd keep this open to encourage more testing until 1.3.7.

**Comment by ds-sloth** [comment]
I did some UI-side work improving this, using work from the new character select screen. How does it look to you?

[Scr_2024-07-29_13-27-44.webm](https://github.com/user-attachments/assets/410d8ffb-7d19-4b54-8be5-78d81fcf8ea6)
