### ISSUE TITLE
[Enhancement] [Compatibility] Add a setting to prevent NPCs from working outside of 800x600 by default.

### ISSUE THREAD

**Issue by SkullGamer205** [TheXTech/TheXTech#710]
Add a setting to prevent NPCs from working outside of 800x600 **by default**.

This setting will allow episodes configured for certain timings to work more correctly (Whether it’s Kaizo levels/worlds, or ordinary worlds with small maneuvers).

And in `compat.ini` add the ability to enable 'smart' NPCs (Disable, enable certain, enable)

**Comment by ds-sloth** [comment]
For individual NPCs, you may create an empty attached layer for the NPC. I think that will be an efficient way to signal to the engine that the NPC should use 800x600 logic in the future. We may try to add some UI features to simplify this process for the user.

For the `compat.ini` setting, we previously had a setting like this but removed it because it was confusing. Indeed, there are three possibilities: (1) always use the actually visible camera, (2) use the canonical 800x600 screen's camera for some NPCs, and (3) use the canonical screen's camera for all NPCs. However, these options became confusing and difficult to test in splitscreen mode, so I decided to remove the setting entirely. I would consider adding this setting back if @Wohlstand and @0lhi agree it would be useful.

**Comment by ds-sloth** [comment]
Proposal for steps we take in the 1.3.7 release:
- Add a `compat.ini` option, `dynamic-camera-logic`. If set to false, this limits the playfield to 800x600, and when the playfield is smaller than 800x600, it forces all NPCs to activate when in the 800x600 range.
- Add a new `npc.txt` option, `use-default-cam` (or something similar). This allows the user to force an NPC type to activate when (and only when) in the 800x600 range, at all resolutions.

@SkullGamer205, does that sound good to you?

**Comment by SkullGamer205** [comment]
> Proposal for steps we take in the 1.3.7 release:
> - Add a `compat.ini` option, `dynamic-camera-logic`. If set to false, this limits the playfield to 800x600, and when the playfield is smaller than 800x600, it forces all NPCs to activate when in the 800x600 range.
> - Add a new `npc.txt` option, `use-default-cam` (or something similar). This allows the user to force an NPC type to activate when (and only when) in the 800x600 range, at all resolutions.
> 
> @SkullGamer205, does that sound good to you?

Yoooo, thats cool.

But maybe rename `use-default-cam` to `npc-use-default-cam`, or `npc-use-def-cam` or `npc-use-old-cam` ?

**Comment by ds-sloth** [comment]
> What about `dynamic-camera-logic`?

Setting `dynamic-camera-logic = 0` will make it so that <800x600 resolutions are still available (but the NPCs will activate using 800x600). >800x600 resolutions will play with a centered 800x600 camera.

If you want the camera to be bigger than 800x600, but want your NPCs to activate using 800x600, then you should set the `npc.txt` option instead.

**Comment by ds-sloth** [comment]
This compat option should now be available on development builds.
