### ISSUE TITLE
Border won't work if replaced backdrop.png

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#769]
![Scr_2024-06-24_11-31-00_(1)](https://github.com/TheXTech/TheXTech/assets/37089530/644781aa-4d72-4c16-b828-0ef788314333)
![Backdrop](https://github.com/TheXTech/TheXTech/assets/37089530/d9a888de-84a6-496d-b38d-ee44960df189)

This means it requires copying the respective border files from the "graphics\ui" folder!

**Comment by ds-sloth** [comment]
This is the current intended behavior, so that if Backdrop.png gets replaced, it won't be drawn with an incompatible border. The same thing happens if WorldMapFrame_Tile.png gets replaced.

@Wohlstand, do you think we should change this? I don't have a strong opinion here, and maybe it's more intuitive if each image can be replaced individually.

**Comment by Wohlstand** [comment]
I guess, the problem that this behaviour wasn't documented, and therefore treated as an invalid. :thinking:
