### ISSUE TITLE
4-player shared mode breaks the game

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#781]
### Describe the issue

When 4-player shared is enable and play test a level with the smallest level size this happens. 
![image](https://github.com/user-attachments/assets/4244e3c4-809e-4266-9f78-bb8c1600cd5c)
I have the level so I will teleport from one side of the screen to the other and it dosen't happen, also breaks camera scrolling down after flying up. 4-player mode should be disabled intierly as it is unusable on 3ds, unless download play or some online thing is done.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

bb07af2

### Platform

3DS

### Processor architecture

None

**Comment by ds-sloth** [comment]
Hi, there are two possible issues here:
- The cheat codes for multiplayer are currently broken because of some experiments we are doing to test future NetPlay support. It looks like that is affecting you here. I am currently working on a fix for this.
- The editor's level test code may currently create the incorrect number of players (with the same cause). I am also trying to fix this.

Neither of these is cause by the 4-player shared mode itself; the game just doesn't know how many players are currently present.

**Comment by ds-sloth** [comment]
Thanks again for this report!

It took a lot of work but I believe I have fixed each of these two issues. Please test a new build when it is available and let me know if your problem is resolved.

**Comment by Trickiy** [comment]
No problem. (:

**Comment by ds-sloth** [comment]
Fantastic, thanks a lot for confirming!
