### ISSUE TITLE
luma screenshots duped in editor

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#794]
### Describe the issue

Sometimes when I take a screenshot in the editor the top and bottom screenshots will be the same.
![image](https://github.com/user-attachments/assets/2d654b6c-a68f-454d-9f38-5f1ad1c35787)
![image](https://github.com/user-attachments/assets/47765f1d-e5ea-4ab6-97f2-527d36ebca14)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Happens randomly, often

### Version

1.3.7-dev

### Version Hash

#29ca69c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thanks for the report! This is interesting, but I don't think it's our problem.

Luma's interrupt handler can be called at an arbitrary time (by design), and the select key is used to swap screens on our side. It is possible for the interrupt handler to call the same frame that the screens swap, after the top screen has been redrawn and before the bottom screen has been redrawn.

If you want to avoid this happening, then I'd suggest you press and hold the Select key first when triggering the Luma key combination. Does that make this occur less frequently for you?

**Comment by Trickiy** [comment]
That's one way to get around the problem, yes it would make it not happen but I found that if I hold L trigger and ^ first then select. Both works so its not that big of a issue.
