### ISSUE TITLE
Lowsers Conquest: weird clouds

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#822]
### Describe the issue

In the level Stardust Lands the cloud platforms are off centered.
![2024-09-04_16-28-21 689_top](https://github.com/user-attachments/assets/7273bc99-68ae-44ef-8597-426467720b3b)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thanks for the note! This is the combined fault of the episode (which called the textures `Block-XXX.png` instead of `block-XXX.png` -- this is acceptable but not preferred), and the asset conversion script which didn't recognize the custom textures. I'll update the conversion scripts and I already sent you a new version of the asset pack over Discord.

**Comment by Trickiy** [comment]
Thanks!

**Comment by Trickiy** [comment]
After testing the cloud platforms look normal.
![2024-09-04_21-50-23 104_top](https://github.com/user-attachments/assets/caafb555-b608-491c-8beb-2ba03bca8b5f)
and as I played I started to think that the same issue may apply to the enemies death animations.

**Comment by ds-sloth** [comment]
Great! (And I don't think that's right, none of the enemy death animations had uppercase names.)
