### ISSUE TITLE
Piranha plants attached to pipes break

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#829]
### Describe the issue

When I have a piranha attached to a pipe above it the pipes will stop moving after I stand atop were the piranha is at.

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Happens randomly, often

### Version

1.3.7-dev

### Version Hash

#590838a

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

### Example Case

[moving pipe.zip](https://github.com/user-attachments/files/16919083/moving.pipe.zip)

**Comment by ds-sloth** [comment]
Thanks for the report! This test case seems to be incomplete -- it doesn't have any plants. But I replicated what I believe you are describing, and it is the correct behavior.

The plant still uses plant AI -- including not coming out when the player is nearby. The rest of the pipes should follow the plant's position. There is some minor 'jank' here, but the plant logic looks totally correct to me.

If you want the pipes to always move up and down, you should use two events in a cycle that move the layer up and down at the same speed as each other.

![Scr_2024-09-24_18-54-18](https://github.com/user-attachments/assets/9db3c3a7-85be-47b7-814b-38c0e76ad75e)

Please let me know if you were actually thinking of a different case.

**Comment by Trickiy** [comment]
The pirana plant it is there in the example, hiding under the orange pipe and behind the layer the wood blocks are on.

**Comment by ds-sloth** [comment]
There's a vanilla peculiarity affecting this case, where the plant doesn't spawn successfully when the level is played normally (but previously spawned when the level was opened as a level test due to a bug I just fixed). I want to understand this case better because it seems very strange that the plant would despawn.

**Comment by ds-sloth** [comment]
I've figured out the situation here -- it's actually a more general case: because of the way despawned plants' hitbox is represented, plants that touch the bottom of the screen will never spawn at all. This is an interesting peculiarity and I'm not certain whether it's necessary to fix it. But your original issue was about the fact that plants stop moving when a player is above them, and that is normal and expected behavior. I'll make a new issue to discuss this new case.

**Comment by Trickiy** [comment]
> But your original issue was about the fact that plants stop moving when a player is above them

Whoops sorry I've never been the greatst at explaining things by nature. I am slowly improving as I find new things though.

**Comment by ds-sloth** [comment]
That's okay, it was clear earlier, I said this because there is another, related issue that I found (and linked to this one).
