### ISSUE TITLE
[Bug] Tokens don't get counted in tracker when collected in nonstandard way

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#861]
### Describe the issue

When collecting a token with Yellow or Purple Yoshi ability, or bumping the token from a block below it, the token will make a coin effect and not appear in the HUD.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-beta

### Platform

Android

### Processor architecture

None

### Example Case

[coins.zip](https://github.com/user-attachments/files/17819522/coins.zip)

**Comment by ds-sloth** [comment]
Thank you for the report! This is actually the desired behavior because we treat medals (tokens) the same way as SMBX 1.3.

If a medal gives the player score / 1-UP and increment the medal counter in SMBX 1.3, then it should get counted by our engine. 

But if a medal is destroyed in any other way (including the cases you mentioned as well as lava and and falling offscreen) then it won't be counted by our engine.

I'm labeling this as WONTFIX for now because our main goal is to match SMBX 1.3 logic, but it may be possible to convince me to change it.

**Comment by Wohlstand** [comment]
This case is weird, and it's unfair to not count score here. I may guess do this update for modern mode only then. What do you think,  @ds-sloth ?

**Comment by ds-sloth** [comment]
I'm not certain. These do seem like cases where the player would expect to collect the coin.

But in general the standard for fixing vanilla peculiarities is very high. Something must be unambiguously *broken* about the original behavior. Do you think that is the case here?

**Comment by Wohlstand** [comment]
This isn't so physics, but it's a logic, just how taken bonus gets counted, I don't thing that might break something other.

**Comment by ds-sloth** [comment]
Okay, I agree that this is probably surprising to players, and it shouldn't break anything else. I'm familiar with this code so I will implement it very quickly now.

**Comment by ds-sloth** [comment]
Should be fixed now.

Modern:

<img src="https://github.com/user-attachments/assets/a6ec72c0-5fbd-42ff-b89a-89014c3fe7c3" width="400" height="300">


Classic:

<img src="https://github.com/user-attachments/assets/49a295dc-aec9-4fa2-b90f-84aef5f2ce0b" width="400" height="300">

Please let me know if this now works as you expect!

**Comment by ds-sloth** [comment]
Closing this due to lack of response. It's working on our side. Thank you for the report!
